name: Deploy to InfinityFree

on:
  push:
    branches:
      - main   # runs every time you push to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            config.php
            config.example.php
